version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    volumes:
      - ../src:/code
      - ../src:/code/src
    ports:
      - "5005:80"
